# -*- coding: utf-8 -*-
"""DataAnalysis_HRAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubDQjU_P5PKx3ERHPD-htaUigAOLE6GE
"""

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf
import numpy as np
from google.colab import drive
import json
from tensorflow.keras import layers

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
# %matplotlib inline

#Preprocessing   여기는 데이터 불러오는 파트라 노상관
import pandas as pd

with open('/content/drive/MyDrive/Trialdata_Ordinal.csv',mode = 'r') as data:
  trialdata = pd.read_csv(data)

data = np.array(trialdata)

from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from pandas import Series, DataFrame as df

enc = OrdinalEncoder()
enc.fit(trialdata[["Height","IQ","Education", "Sight","3KM","Pushup"]])
trialdata[["Height","IQ","Education", "Sight","3KM","Pushup"]] = enc.transform(trialdata[["Height","IQ","Education", "Sight","3KM","Pushup"]])

enc = OrdinalEncoder()
enc.fit(trialdata[["Major","LeadorFollow","IorE", "Hobby","Speciality","Job"]])
trialdata[["Major","LeadorFollow","IorE", "Hobby","Speciality","Job"]] = enc.transform(trialdata[["Major","LeadorFollow","IorE", "Hobby","Speciality","Job"]])

ss = StandardScaler()
ss.fit(trialdata[["Injustice","Absurdity","JobHappiness","JobIntesity","JobScore"]])
trialdata[["Injustice","Absurdity","JobHappiness","JobIntesity","JobScore"]] = ss.transform(trialdata[["Injustice","Absurdity","JobHappiness","JobIntesity","JobScore"]])

from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(trialdata, test_size=0.2,random_state=20)

print('The size of training data is: {} \nThe size of testing data is: {}'.format(len(train_data), len(test_data)))

train_data.hist(bins=50, figsize=(15,10))
plt.show()

# Checking feature correlation

corr = train_data.corr()

## Visualizing correlation

plt.figure(figsize=(12,7))

sns.heatmap(corr,annot=True,cmap='crest')

X_train = train_data.drop('JobScore', axis=1)
y_train = train_data['JobScore']

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

scale_pipe = Pipeline([
    ('scaler', StandardScaler())

])

X_train_scaled = scale_pipe.fit_transform(X_train)

from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(min_samples_split=2,bootstrap=False, random_state=42,n_jobs=-1)

forest_reg.fit(X_train_scaled, y_train)

from sklearn.metrics import mean_squared_error

def predict(input_data,model,labels):
    """
    Take the input data, model and labels and return predictions

    """

    preds = model.predict(input_data)
    mse = mean_squared_error(labels,preds)
    rmse = np.sqrt(mse)
    rmse

    return rmse

predict(X_train_scaled, forest_reg, y_train)

from sklearn.model_selection import GridSearchCV

params_grid = {
    'n_estimators':[100,200,300,400,500],
    'max_leaf_nodes':list(range(0,50))}

#refit is true by default. The best estimator is trained on the whole dataset

grid_search = GridSearchCV(RandomForestRegressor(min_samples_split=2,bootstrap=False,random_state=42), params_grid, verbose=1, cv=5)

grid_search.fit(X_train_scaled, y_train)

grid_search.best_params_

grid_search.best_estimator_

forest_best = grid_search.best_estimator_

predict(X_train_scaled, forest_best, y_train)

feat_import = forest_best.feature_importances_

feat_dict ={

    'Features': X_train.columns,
    'Feature Importance': feat_import
}

#feat_dict=sorted(feat_dict, key=lambda k: (feat_dict[k], k))



pd.DataFrame(feat_dict)

