# -*- coding: utf-8 -*-
"""Final_HRAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fwSHvcMxLdmmWBXAfsgMUi8LH81KNU2
"""

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf
import numpy as np
from google.colab import drive
import json
from tensorflow.keras import layers

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
# %matplotlib inline

#korean patch

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt

plt.rc('font', family='NanumBarunGothic')

#Preprocessing   여기는 데이터 불러오는 파트라 노상관
import pandas as pd

with open('/content/drive/MyDrive/Trialdata_Ordinal.csv',mode = 'r') as data:
  trialdata = pd.read_csv(data)

data = np.array(trialdata)

# 데이터 전처리작업.. 총 3가지 기법을 씀
# 1. 오디날 인코딩 - 상하관계가 있는 이산형 자료
# 2. 원핫 인코딩 - 상하관계가 없는 이산형 자료
# 3. 표준화 - 연속형 자료

from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from pandas import Series, DataFrame as df

enc = OrdinalEncoder()
enc.fit(trialdata[["Height","IQ","Education", "Sight","3KM","Pushup"]])
trialdata[["Height","IQ","Education", "Sight","3KM","Pushup"]] = enc.transform(trialdata[["Height","IQ","Education", "Sight","3KM","Pushup"]])

onehot = OneHotEncoder()
#Fit onehot encoder
onehot.fit(trialdata[["Major","LeadorFollow","IorE", "Hobby","Speciality","Job"]])
#Transform the selected columns and convert to an array
encoded_data = onehot.transform(trialdata[["Major","LeadorFollow","IorE", "Hobby","Speciality","Job"]]).toarray()
#Create column names for the encoded data
column_names = onehot.get_feature_names_out(["Major","LeadorFollow","IorE", "Hobby","Speciality","Job"])
#Create a new DataFrame with the encoded data
encoded_df = pd.DataFrame(encoded_data, columns=column_names)
#Concatenate the encoded DataFrame with the original DataFrame
trialdata = pd.concat([trialdata, encoded_df], axis=1)
#Remove the original columns
trialdata = trialdata.drop(["Major","LeadorFollow","IorE", "Hobby","Speciality","Job"], axis=1)

ss = StandardScaler()
ss.fit(trialdata[["Injustice","Absurdity","JobHappiness","JobIntesity","JobScore"]])
trialdata[["Injustice","Absurdity","JobHappiness","JobIntesity","JobScore"]] = ss.transform(trialdata[["Injustice","Absurdity","JobHappiness","JobIntesity","JobScore"]])

#데이터 쪼개기

X = trialdata.drop(['JobScore'], axis=1)

y = trialdata['JobScore']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 42)

#데이터 쪼개기 2 인데 보면 test size 가 0.3. 이건 지금 가지고있는데이터를 30% 실전 70% 학습용으로 나눈다 생각하면됨

# import Random Forest classifier
from sklearn.ensemble import RandomForestRegressor # Changed to RandomForestRegressor

# instantiate the classifier
rfr = RandomForestRegressor(n_estimators=200, random_state=50, max_depth=50) # Changed to RandomForestRegressor
# fit the model

rfr.fit(X_train, y_train)

# Predict the Test set results

y_pred = rfr.predict(X_test)

# Check accuracy score

from sklearn.metrics import mean_squared_error # Changed to a suitable metric for regression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score # Changed to a suitable metric for regression

print('Model mean squared error : {0:0.4f}'. format(mean_squared_error(y_test, y_pred))) # Changed to a suitable metric for regression
print('Model mean absolute error : {0:0.4f}'. format(mean_absolute_error(y_test, y_pred))) # Changed to a suitable metric for reg

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

# Assuming regressor is your trained Random Forest model
# Pick one tree from the forest, e.g., the first tree (index 0)
tree_to_plot = rfr.estimators_[0]

# Plot the decision tree
plt.figure(figsize=(20, 10))
plot_tree(tree_to_plot, feature_names=trialdata.columns.tolist(), filled=True, rounded=True, fontsize=10)
plt.title("Decision Tree from Random Forest")
plt.show()

