# -*- coding: utf-8 -*-
"""IMDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nm5sUg3JesmjUZYi9Mm83-HWvn2Yr2bv
"""

from keras.preprocessing import sequence
from keras.datasets import imdb
from keras import layers, models

max_features=20000
maxlen=80
(x_train, y_train), (x_test,y_test) = imdb.load_data(num_words=max_features)
x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = sequence.pad_sequences(x_test, maxlen=maxlen)



x = layers.Input((maxlen, ))
h = layers.Embedding(max_features, 128)(x)
h = layers.SimpleRNN(128)(h)
y= layers.Dense(1, activation='sigmoid')(h)

model = models.Model(x,y)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
batch_size = 32
epochs = 30
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          validation_data=(x_test, y_test))

model.predict(x_test)

x_test[0]

